[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hero_anchor_program = "DEXA1SPRbDf4tugo6TeePTqUnN9QNSiz1XRRdaMosWPa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
